### ISSUE TITLE
File db/creat_table is not complete?

### ISSUE THREAD

**Issue by Cristliu** [mishal23/virtual-clinic#12]
I can not find "Action" and "MedicalInfo"

**Comment by mishal23** [comment]
Hey @Cristliu, yeah it's not the complete db creation file. Could you please use the Django migrations? The steps are defined here: https://github.com/mishal23/virtual-clinic/blob/master/Installation.md

Please let me know if that solves the issue

**Comment by Cristliu** [comment]
Thank you very much, using the Django migrations works fine. But sorry, is there only the patient interface in the system?
Could you please tell me where I can find the interface for the doctor's visit?

**Comment by mishal23** [comment]
Hey, please add a user with role as "doctor", and once you've added, on login you'll see the doctor's interface.

To add a user with role "doctor", you'll need an admin account (admin account has to be compulsory created on the first time setup), once done you can see the interface.

Let me know if that helps, otherwise I'll try to define more steps.

**Comment by mishal23** [comment]
Hey, I hope it has been cleared for you, will be closing the issue, feel free to open a new issue incase you need further help
